/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGenerationsRouteImport } from './routes/_authenticated/generations'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'
import { Route as AuthenticatedTemplatesIdEditRouteImport } from './routes/_authenticated/templates.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGenerationsRoute =
  AuthenticatedGenerationsRouteImport.update({
    id: '/generations',
    path: '/generations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdEditRoute =
  AuthenticatedTemplatesIdEditRouteImport.update({
    id: '/templates/$id/edit',
    path: '/templates/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generations': typeof AuthenticatedGenerationsRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/templates/$id/edit': typeof AuthenticatedTemplatesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generations': typeof AuthenticatedGenerationsRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/templates/$id/edit': typeof AuthenticatedTemplatesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/generations': typeof AuthenticatedGenerationsRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/templates/$id/edit': typeof AuthenticatedTemplatesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/generations'
    | '/templates/new'
    | '/templates/'
    | '/templates/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/generations'
    | '/templates/new'
    | '/templates'
    | '/templates/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/generations'
    | '/_authenticated/templates/new'
    | '/_authenticated/templates/'
    | '/_authenticated/templates/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/generations': {
      id: '/_authenticated/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof AuthenticatedGenerationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id/edit': {
      id: '/_authenticated/templates/$id/edit'
      path: '/templates/$id/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof AuthenticatedTemplatesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGenerationsRoute: typeof AuthenticatedGenerationsRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedTemplatesIdEditRoute: typeof AuthenticatedTemplatesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGenerationsRoute: AuthenticatedGenerationsRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedTemplatesIdEditRoute: AuthenticatedTemplatesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
